#! /bin/bash -f

# Load the modules before running Build
echo Loading modules ... takes half a minute ...

module purge
module load intel/19.0.5-fasrc01 impi/2019.5.281-fasrc01 netcdf/4.1.3-fasrc02

./Build.csh >& Build.log &  #TODO
echo Build submitted in background
echo Writing logs in Build.log

