#! /bin/bash -f

# Load the modules before running Build
echo Loading modules ... takes half a minute ...

module purge
module load intel/23.0.0-fasrc01 intelmpi/2021.8.0-fasrc01 netcdf-c/4.9.2-fasrc01

./Build.csh >& Build.log &  #TODO
echo Build submitted in background
echo Writing logs in Build.log

